# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

executors:
  node-browsers:
    docker:
      - image: cimg/node:16.17-browsers

jobs:
  setup:
    executor: node-browsers
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: make clean-dependencies
      - run: make deps
      - run: npm run lint
      - run: cp -R conf src node_modules test package.json /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - src
            - node_modules
            - test
            - conf
            - package.json
  test-node:
    executor: node-browsers
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:node
  test-browser:
    executor: node-browsers
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:browser
  build:
    executor: node-browsers
    steps:
      - attach_workspace:
          at: ./
      - run: npm run build

workflows:
  version: 2
  Implementations:
    jobs:
      - setup
      - test-node:
          requires:
            - setup
      - test-browser:
          requires:
            - setup
      - build:
          requires:
            - setup
